#reload config
bind=SUPER+SHIFT,r,reload_config

# menu and terminal
bind=SUPER,d,spawn,rofi -show drun
bind=SUPER,Return,spawn,foot
bind=ALT,y,spawn,foot -e yazi
bind=ALT,g,spawn,foot -D ~/ani-cli -e ./ani-cli

# exit/kill client
bind=SUPER,p,quit
bind=SUPER+SHIFT,q,killclient,

#increase/decrease master
bind=SUPER,w,incnmaster,1
bind=SUPER,s,incnmaster,-1
bind=SUPER,e,zoom,

# switch window focus
bind=SUPER,tab,focusstack,next
bind=SUPER+SHIFT,tab,focuslast
bind=SUPER,Left,focusdir,left
bind=SUPER,Right,focusdir,right
bind=SUPER,Up,focusdir,up
bind=SUPER,Down,focusdir,down
bind=SUPER,H,focusdir,left
bind=SUPER,L,focusdir,right
bind=SUPER,K,focusdir,up
bind=SUPER,J,focusdir,down

# swap window
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right
bind=SUPER+SHIFT,K,exchange_client,up
bind=SUPER+SHIFT,J,exchange_client,down
bind=SUPER+SHIFT,H,exchange_client,left
bind=SUPER+SHIFT,L,exchange_client,right

# movefloatingwin
bind=CTRL+SHIFT,Up,movewin,+0,-50
bind=CTRL+SHIFT,Down,movewin,+0,+50
bind=CTRL+SHIFT,Left,movewin,-50,+0
bind=CTRL+SHIFT,Right,movewin,+50,+0

# tag switch
#bind=CTRL,Left,viewtoleft_have_client,0
#bind=CTRL,Right,viewtoright_have_client,0
#bind=CTRL+SUPER,Left,tagtoleft,0
#bind=CTRL+SUPER,Right,tagtoright,0
# bind=SUPER,Left,viewtoleft,0
# bind=SUPER,Right,viewtoright,0

# resizewin
bind=CTRL+ALT,Up,resizewin,+0,-50
bind=CTRL+ALT,Down,resizewin,+0,+50
bind=CTRL+ALT,Left,resizewin,-50,+0
bind=CTRL+ALT,Right,resizewin,+50,+0

# switch window status
bind=SUPER,g,toggleglobal,
bind=ALT,Tab,toggleoverview,
bind=SUPER+SHIFT,space,togglefloating,
bind=SUPER+SHIFT,f,togglemaximizescreen,
bind=SUPER,f,togglefullscreen,
bind=ALT+SHIFT,f,togglefakefullscreen,
bind=SUPER+SHIFT,Z,minimized,
bind=SUPER+SHIFT,I,restore_minimized
bind=SUPER,z,toggle_scratchpad
bind=SUPER,o,toggleoverlay,

# Mouse Button Bindings
# NONE mode key only work in ov mode
mousebind=SUPER,btn_left,moveresize,curmove
# mousebind=NONE,btn_middle,togglemaximizescreen,0
mousebind=SUPER,btn_right,moveresize,curresize
mousebind=NONE,btn_left,toggleoverview,1
mousebind=NONE,btn_right,killclient,0

# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

# scroller layout
bind=ALT,e,set_proportion,1.0
bind=ALT,x,switch_proportion_preset,

# Layouts
bind=SUPER,t,setlayout,tile
bind=SUPER,v,setlayout,vertical_grid
bind=SUPER,c,setlayout,scroller
bind=SUPER,n,switch_layout
bind=SUPER,a,togglegaps

#screenshots/picker
bind=SUPER+SHIFT,s,spawn,grimshot copy area 
bind=SUPER+SHIFT,a,spawn,grimshot copy active --notify 
bind=SUPER+SHIFT,d, spawn, grimshot copy output --notify
bind=SUPER+SHIFT,x,spawn,hyprpicker --autocopy

#brightness
bind=NONE,XF86MonBrightnessUp,spawn,brightnessctl set +10%
bind=NONE,XF86MonBrightnessDown,spawn,brightnessctl set 10%-

#volume
bind=NONE,XF86AudioRaiseVolume,spawn,pactl set-sink-volume @DEFAULT_SINK@ +5%
bind=NONE,XF86AudioLowerVolume,spawn,pactl set-sink-volume @DEFAULT_SINK@ -5%
bind=NONE,XF86AudioMute,spawn,pactl set-sink-mute @DEFAULT_SINK@ toggle
