windowrule=unfocused_opacity:0.8,focused_opacity:0.8,appid:^foot$
windowrule=unfocused_opacity:1.0,focused_opacity:1.0,appid:^thunar$
windowrule=unfocused_opacity:0.8,focused_opacity:0.8,appid:^kitty$
windowrule=unfocused_opacity:0.8,focused_opacity:0.8,appid:^alacritty$
windowrule=unfocused_opacity:1.0,focused_opacity:1.0,appid:^hyprshot$

#layer rule
layerrule=noblur:1,noanim:1,layer_name:selection
layerrule=noshadow:1,layer_name:swaync-control-center
layerrule=noshadow:1,layer_name:swaync-notification-window
layerrule=noblur:1,noanim:1,layer_name:dimland_layer
layerrule=animation_type_open:zoom,layer_name:launcher
layerrule=animation_type_close:zoom,layer_name:launcher
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi
layerrule=noanim:1,noblur:1,noshadow:1,layer_name:hyprpicker
layerrule=noanim:1,layer_name:showkeys
layerrule=noanim:1,layer_name:wofi
layerrule=noshadow:1,layer_name:waybar
layerrule=animation_type_open:fade,layer_name:swaync-control-center
layerrule=animation_type_close:fade,layer_name:swaync-control-center
layerrule=animation_type_open:fade,layer_name:swayosd
layerrule=animation_type_close:fade,layer_name:swayosd
# layerrule=animation_type_open:fade,layer_name:logout_dialog
# layerrule=animation_type_close:fade,layer_name:logout_dialog
# windowrule=isfloating:1,appid:.*
