[main]
font=JetBrainsMono Nerd Font:size=11
#font=LavenderNerd-Regular:size=14
#font=Terminus (TTF):size=13
resize-by-cells=no #fixes that weird floating resize glitch that adds a transparent space between the border and the terminal, its fuckin annoying

[desktop-notifications]
command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}

[cursor]
style=beam #block/beam/underline
blink=yes

[main]
include=~/.config/foot/base16dark

#search-box-no-match=11111b f38ba8
#search-box-match=cdd6f4 313244

#jump-labels=11111b fab387
#urls=89b4fa

[url]
launch=xdg-open ${url}

[key-bindings]
scrollback-up-page=Shift+Page_Up
scrollback-down-page=Shift+Page_Down
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+v XF86Paste
